export const destinations = [
  {
    id: 1,
    destinationName: "KidZania Delhi NCR",
    price: "₹790 + GST",
    ourPrice: "",
    profit: 50,
    address: "Entertainment City, Sector 18, Noida, Uttar Pradesh – 201301",
  },
  {
    id: 2,
    destinationName: "Boom Bastic",
    price: "Bambino: ₹950 + GST; Boombastic: ₹1350 + GST",
    ourPrice: "",
    profit: 50,
    address: "JMD Empire, C-5/1, Coupe, Jangrpura, Gurugram – 122001",
  },
  {
    id: 3,
    destinationName: "Oh!Max Dream World",
    price: "₹910 + GST",
    ourPrice: "",
    profit: 50,
    address: "Beeta 2, H-Block, Greater Noida",
  },
  {
    id: 4,
    destinationName: "Bounce Gurugram",
    price:
      "Weekdays: KG ₹650, Class 1–10 ₹800, Class 11+ ₹900; Weekends: KG ₹750, Class 1–10 ₹900, Class 11+ ₹1000 (GST Incl.)",
    ourPrice: "",
    profit: 50,
    address: "Bounce Gurugram",
  },
  {
    id: 5,
    destinationName: "Adventure Island",
    price: "₹400 + GST",
    ourPrice: "",
    profit: 50,
    address: "Metro Walk, Sector 10, Rohini, New Delhi",
  },
  {
    id: 6,
    destinationName: "Fun N Food Water Park",
    price: "₹900 + GST",
    ourPrice: "",
    profit: 50,
    address: "Old Delhi Gurgaon Road, Kapashera, New Delhi – 110097",
  },
  {
    id: 7,
    destinationName: "Mojoland",
    price: "Single: ₹370; Any 2: ₹530; Any 3: ₹650; All 4: ₹770 (+GST)",
    ourPrice: "",
    profit: 50,
    address: "Near Bhigan Toll, NH-44, Murthal, Sonipat, Haryana",
  },
  {
    id: 8,
    destinationName: "Worlds of Wonder Water Park",
    price: "₹850 + GST",
    ourPrice: "",
    profit: 50,
    address:
      "Gate No. 11, Maharaja Agrasen Marg, Sector 38, Noida, Uttar Pradesh – 201303",
  },
  {
    id: 9,
    destinationName: "Runway 1 + SkyJumper",
    price: "₹600 + GST",
    ourPrice: "",
    profit: 50,
    address: "Metro Walk Mall, Sector 10, Rohini, New Delhi",
  },
  {
    id: 10,
    destinationName: "Museum of Illusions",
    price: "₹450 + GST",
    ourPrice: "",
    profit: 50,
    address:
      "A-30/33, 1st Floor, A Block, Inner Circle, Connaught Place, New Delhi – 110001",
  },
  {
    id: 11,
    destinationName: "Same Day Adventure Camp (School Campus)",
    price: "With Meal: ₹499 + GST; Without Meal: ₹249 + GST",
    ourPrice: "",
    profit: 50,
    address: "School Campus",
  },
  {
    id: 12,
    destinationName: "Astro Night Camping",
    price: "₹1699 (GST Included)",
    ourPrice: "",
    profit: 50,
    address: "School Campus",
  },
  {
    id: 13,
    destinationName: "The Game Palacio",
    price: "Pitampura: ₹1000 + GST; Ansal Plaza: ₹1100 + GST",
    ourPrice: "",
    profit: 50,
    address: "Pitampura, West Delhi / Ansal Plaza, New Delhi",
  },
  {
    id: 14,
    destinationName: "EOD Adventure Park",
    price: "Pre-Nursery–Class 2: ₹550 + GST; Class 3+: ₹600 + GST",
    ourPrice: "",
    profit: 50,
    address: "Sanjay Lake, Mayur Vihar Phase 1, Delhi",
  },
] as const;
