export const defaultInventoryItems = {
  messName: "ITS Greater Noida",

  items: [
    { item_id: "ITM01", item_name: "Dhaniya Powder", current_stock: 6, unit: "kg" },
    { item_id: "ITM02", item_name: "Haldi", current_stock: 4, unit: "kg" },
    { item_id: "ITM03", item_name: "Mirch", current_stock: 10, unit: "kg" },
    { item_id: "ITM04", item_name: "Garam Masala", current_stock: 4, unit: "pkt" },
    { item_id: "ITM05", item_name: "Chana Masala", current_stock: 4, unit: "pkt" },
    { item_id: "ITM06", item_name: "Kitchen King", current_stock: 10, unit: "pkt" },
    { item_id: "ITM07", item_name: "Degi Mirch", current_stock: 5, unit: "pkt" },
    { item_id: "ITM08", item_name: "Sambhar Masala", current_stock: 4, unit: "pkt" },
    { item_id: "ITM09", item_name: "Kala Namak", current_stock: 1, unit: "pkt" },
    { item_id: "ITM10", item_name: "Amchur", current_stock: 4, unit: "kg" },
    { item_id: "ITM11", item_name: "Ajinomoto", current_stock: 7, unit: "pkt" },
    { item_id: "ITM12", item_name: "Peri Peri Masala", current_stock: 2, unit: "pkt" },
    { item_id: "ITM13", item_name: "Rooh Afza", current_stock: 3, unit: "bottle" },
    { item_id: "ITM14", item_name: "Oregano Masala", current_stock: 1, unit: "pkt" },
    { item_id: "ITM15", item_name: "Achar Masala", current_stock: 1, unit: "kg" },
    { item_id: "ITM16", item_name: "Baking Powder", current_stock: 4, unit: "dibba" },
    { item_id: "ITM17", item_name: "Custard Powder", current_stock: 300, unit: "g" },
    { item_id: "ITM18", item_name: "Achar", current_stock: 5, unit: "dibba" },
    { item_id: "ITM19", item_name: "Coffee Powder", current_stock: 25, unit: "kg" },
    { item_id: "ITM20", item_name: "Tea Powder", current_stock: 20, unit: "kg" },
    { item_id: "ITM21", item_name: "Corn Flakes", current_stock: 5, unit: "pkt" },
    { item_id: "ITM22", item_name: "Refined Oil", current_stock: 5, unit: "tin" },
    { item_id: "ITM23", item_name: "Ghee", current_stock: 3, unit: "tin" },
    { item_id: "ITM24", item_name: "Surf (Nirma)", current_stock: 3, unit: "kg" },
    { item_id: "ITM25", item_name: "Imli", current_stock: 0.5, unit: "kg" },
    { item_id: "ITM26", item_name: "Jam", current_stock: 3, unit: "kg" },
    { item_id: "ITM27", item_name: "Vinegar", current_stock: 4, unit: "L" },
    { item_id: "ITM28", item_name: "Green Chilli Sauce", current_stock: 7, unit: "L" },
    { item_id: "ITM29", item_name: "Tomato Ketchup", current_stock: 25, unit: "kg" },
    { item_id: "ITM30", item_name: "Zeera (Whole)", current_stock: 400, unit: "g" },
    { item_id: "ITM31", item_name: "Clean Rep", current_stock: 2, unit: "pcs" },
    { item_id: "ITM32", item_name: "Papad", current_stock: 6, unit: "pkt" },
    { item_id: "ITM33", item_name: "Chaat Masala", current_stock: 1, unit: "pkt" },
    { item_id: "ITM34", item_name: "Yellow Color", current_stock: 3, unit: "dibba" },
    { item_id: "ITM35", item_name: "Red Color", current_stock: 1, unit: "dibba" },
    { item_id: "ITM36", item_name: "Sabut Dhaniya", current_stock: 1, unit: "kg" },
    { item_id: "ITM37", item_name: "Urad Dhoba", current_stock: 60, unit: "kg" },
    { item_id: "ITM38", item_name: "Kabuli Chana", current_stock: 60, unit: "kg" },
    { item_id: "ITM39", item_name: "Urad Chilka", current_stock: 35, unit: "kg" },
    { item_id: "ITM40", item_name: "Urad Sabut", current_stock: 40, unit: "kg" },
    { item_id: "ITM41", item_name: "Mix Dal", current_stock: 45, unit: "kg" },
    { item_id: "ITM42", item_name: "Rajma", current_stock: 30, unit: "kg" },
    { item_id: "ITM43", item_name: "Moong Talai", current_stock: 41, unit: "kg" },
    { item_id: "ITM44", item_name: "Chana Dal", current_stock: 45, unit: "kg" },
    { item_id: "ITM45", item_name: "Soya Badi", current_stock: 1, unit: "bori" },
    { item_id: "ITM46", item_name: "Kali Masoor", current_stock: 28, unit: "kg" },
    { item_id: "ITM47", item_name: "Biryani Rice", current_stock: 10, unit: "bori" },
    { item_id: "ITM48", item_name: "Macroni", current_stock: 40, unit: "kg" },
    { item_id: "ITM49", item_name: "Sevai/Simayi", current_stock: 2, unit: "bori" },
    { item_id: "ITM50", item_name: "Poha", current_stock: 2, unit: "bori" },
    { item_id: "ITM51", item_name: "Aata", current_stock: 22, unit: "bori" },
    { item_id: "ITM52", item_name: "Rice", current_stock: 7, unit: "bori" },
    { item_id: "ITM53", item_name: "Dosa Rice", current_stock: 1, unit: "bori" },
    { item_id: "ITM54", item_name: "Sugar", current_stock: 90, unit: "kg" },
    { item_id: "ITM55", item_name: "salt", current_stock: 75, unit: "kg" },
    { item_id: "ITM56", item_name: "Besan", current_stock: 1, unit: "bori" },
    { item_id: "ITM57", item_name: "Maida", current_stock: 4, unit: "bori" },
    { item_id: "ITM58", item_name: "Ararot", current_stock: 1, unit: "bori" },
    { item_id: "ITM59", item_name: "Vcrmicilli", current_stock: 0, unit: "pcs" },
    { item_id: "ITM60", item_name: "Carrot", current_stock: 0, unit: "kg" },
    { item_id: "ITM61", item_name: "Beans", current_stock: 0, unit: "kg" },
    { item_id: "ITM62", item_name: "onion", current_stock: 0, unit: "kg" },
    { item_id: "ITM63", item_name: "tomato", current_stock: 0, unit: "kg" },
    { item_id: "ITM64", item_name: "Capcicum", current_stock: 0, unit: "kg" },
    { item_id: "ITM65", item_name: "Peas", current_stock: 0, unit: "kg" },
    { item_id: "ITM66", item_name: "Red chilli powder", current_stock: 0, unit: "pkt" },
    { item_id: "ITM67", item_name: "Green Chilli", current_stock: 0, unit: "kg" },
    { item_id: "ITM68", item_name: "Potato", current_stock: 0, unit: "kg" },
    { item_id: "ITM69", item_name: "Cucumber", current_stock: 0, unit: "kg" },
    { item_id: "ITM70", item_name: "Lemon", current_stock: 0, unit: "kg" },
    { item_id: "ITM71", item_name: "Kasturi Methi", current_stock: 0, unit: "pkt" },
    { item_id: "ITM72", item_name: "Mithi Dhania", current_stock: 0, unit: "pkt" },
    { item_id: "ITM73", item_name: "Sabut Mirchi", current_stock: 0, unit: "kg" },
    { item_id: "ITM74", item_name: "Rai", current_stock: 0, unit: "kg" },
    { item_id: "ITM75", item_name: "Arhar dal", current_stock: 0, unit: "kg" },
    { item_id: "ITM76", item_name: "Urad Dhuli", current_stock: 0, unit: "kg" },
    { item_id: "ITM77", item_name: "Soda", current_stock: 0, unit: "pkt" },
    { item_id: "ITM78", item_name: "Suji", current_stock: 0, unit: "kg" },
    { item_id: "ITM79", item_name: "Sambhar masala", current_stock: 0, unit: "pkt" },
    { item_id: "ITM80", item_name: "Parval", current_stock: 0, unit: "kg" },
    { item_id: "ITM81", item_name: "paneer", current_stock: 0, unit: "kg" },
    { item_id: "ITM82", item_name: "Cream", current_stock: 0, unit: "pkt" },
    { item_id: "ITM83", item_name: "Butter", current_stock: 0, unit: "pkt" },
    { item_id: "ITM84", item_name: "Hing", current_stock: 0, unit: "dibba" },
    { item_id: "ITM85", item_name: "Pav", current_stock: 0, unit: "pkt" },
    { item_id: "ITM86", item_name: "Anardana", current_stock: 0, unit: "pkt" },
    { item_id: "ITM87", item_name: "chole masala", current_stock: 0, unit: "pkt" },
    { item_id: "ITM88", item_name: "Ajwain", current_stock: 0, unit: "kg" },
    { item_id: "ITM89", item_name: "Bhindi", current_stock: 0, unit: "kg" },
    { item_id: "ITM90", item_name: "Biryani Masala", current_stock: 0, unit: "pkt" }
  ]
};
