export const defaultInventoryItems = {
  messName: "ITS Greater Noida",

  items: [
    { item_id: "ITM01", item_name: "Achari Masala", current_stock: 2, unit: "kg" },
    { item_id: "ITM02", item_name: "Achar", current_stock: 30, unit: "kg" },
    { item_id: "ITM03", item_name: "Ajinomoto", current_stock: 1, unit: "kg" },
    { item_id: "ITM04", item_name: "Ajwain", current_stock: 2, unit: "kg" },
    { item_id: "ITM05", item_name: "Amla", current_stock: 250, unit: "g" },
    { item_id: "ITM06", item_name: "Anardana", current_stock: 1.5, unit: "kg" },
    { item_id: "ITM07", item_name: "Ararot", current_stock: 50, unit: "kg" },
    { item_id: "ITM08", item_name: "Arhar Dal", current_stock: 120, unit: "kg" },
    { item_id: "ITM09", item_name: "Aata", current_stock: 1200, unit: "kg" },
    { item_id: "ITM10", item_name: "Badi Elaichi", current_stock: 200, unit: "g" },
    { item_id: "ITM11", item_name: "Besan", current_stock: 70, unit: "kg" },
    { item_id: "ITM12", item_name: "Bhuna Chana", current_stock: 30, unit: "kg" },
    { item_id: "ITM13", item_name: "Boondi", current_stock: 15, unit: "kg" },
    { item_id: "ITM14", item_name: "Chaat Masala (MDH)", current_stock: 10, unit: "Packet" },
    { item_id: "ITM15", item_name: "Chana Dal", current_stock: 45, unit: "kg" },
    { item_id: "ITM16", item_name: "Chana Masala (MDH)", current_stock: 12, unit: "Packet" },
    { item_id: "ITM17", item_name: "Chawal (Biryani)", current_stock: 120, unit: "kg" },
    { item_id: "ITM18", item_name: "Chilla Moong Dal", current_stock: 5, unit: "kg" },
    { item_id: "ITM19", item_name: "Choti Elaichi", current_stock: 300, unit: "g" },
    { item_id: "ITM20", item_name: "Coconut Powder", current_stock: 2, unit: "Packet" },
    { item_id: "ITM21", item_name: "Corn Flakes", current_stock: 10, unit: "kg" },
    { item_id: "ITM22", item_name: "Curry Patta", current_stock: 1, unit: "kg" },
    { item_id: "ITM23", item_name: "Custard Powder", current_stock: 12, unit: "Packet" },
    { item_id: "ITM24", item_name: "Dalchini", current_stock: 200, unit: "g" },
    { item_id: "ITM25", item_name: "Degi Mirch (MDH)", current_stock: 30, unit: "Packet" },
    { item_id: "ITM26", item_name: "Dhaniya Powder", current_stock: 10, unit: "kg" },
    { item_id: "ITM27", item_name: "Dosa Rice", current_stock: 120, unit: "kg" },
    { item_id: "ITM28", item_name: "Duster", current_stock: 12, unit: "pcs" },
    { item_id: "ITM29", item_name: "Garam Masala (MDH)", current_stock: 25, unit: "Packet" },
    { item_id: "ITM30", item_name: "Ghee", current_stock: 2, unit: "Tin" },
    { item_id: "ITM31", item_name: "Haldi Powder", current_stock: 10, unit: "kg" },
    { item_id: "ITM32", item_name: "Hing", current_stock: 150, unit: "g" },
    { item_id: "ITM33", item_name: "Imli", current_stock: 10, unit: "kg" },
    { item_id: "ITM34", item_name: "Jam", current_stock: 10, unit: "kg" },
    { item_id: "ITM35", item_name: "Jeera Sabut", current_stock: 4, unit: "kg" },
    { item_id: "ITM36", item_name: "Jhaadu", current_stock: 4, unit: "pcs" },
    { item_id: "ITM37", item_name: "Joona", current_stock: 2, unit: "Packet" },
    { item_id: "ITM38", item_name: "Kala Chana", current_stock: 100, unit: "kg" },
    { item_id: "ITM39", item_name: "Kala Namak", current_stock: 10, unit: "kg" },
    { item_id: "ITM40", item_name: "Kali Masoor", current_stock: 30, unit: "kg" },
    { item_id: "ITM41", item_name: "Kali Mirch", current_stock: 250, unit: "g" },
    { item_id: "ITM42", item_name: "Kali Mirch Sabut", current_stock: 8, unit: "kg" },
    { item_id: "ITM43", item_name: "Kasuri Methi", current_stock: 5, unit: "kg" },
    { item_id: "ITM44", item_name: "Kitchen King Masala", current_stock: 25, unit: "Packet" },
    { item_id: "ITM45", item_name: "Lal Mirch Powder", current_stock: 14, unit: "kg" },
    { item_id: "ITM46", item_name: "Lal Mirch Sabut", current_stock: 1, unit: "kg" },
    { item_id: "ITM47", item_name: "Long", current_stock: 250, unit: "g" },
    { item_id: "ITM48", item_name: "Maida", current_stock: 150, unit: "kg" },
    { item_id: "ITM49", item_name: "Markin Cloth", current_stock: 4, unit: "pcs" },
    { item_id: "ITM50", item_name: "Methi Dana", current_stock: 600, unit: "g" },
    { item_id: "ITM51", item_name: "Mix Dal", current_stock: 30, unit: "kg" },
    { item_id: "ITM52", item_name: "Moong Sabut", current_stock: 60, unit: "kg" },
    { item_id: "ITM53", item_name: "Mota Besan", current_stock: 5, unit: "kg" },
    { item_id: "ITM54", item_name: "Mota Magaj", current_stock: 3, unit: "kg" },
    { item_id: "ITM55", item_name: "Murmure", current_stock: 2, unit: "Bag" },
    { item_id: "ITM56", item_name: "Nahane/Kapde Dhone Ka Sabun", current_stock: 72, unit: "pcs" },
    { item_id: "ITM57", item_name: "Namak", current_stock: 100, unit: "kg" },
    { item_id: "ITM58", item_name: "Namkeen (Aloo Bhujia)", current_stock: 4, unit: "kg" },
    { item_id: "ITM59", item_name: "Nirma", current_stock: 100, unit: "kg" },
    { item_id: "ITM60", item_name: "Papad", current_stock: 30, unit: "Packet" },
    { item_id: "ITM61", item_name: "Phenyl", current_stock: 20, unit: "kg" },
    { item_id: "ITM62", item_name: "Pocha", current_stock: 10, unit: "pcs" },
    { item_id: "ITM63", item_name: "Rajma", current_stock: 60, unit: "kg" },
    { item_id: "ITM64", item_name: "Refined Oil", current_stock: 35, unit: "Tin" },
    { item_id: "ITM65", item_name: "Rice", current_stock: 1000, unit: "kg" },
    { item_id: "ITM66", item_name: "Ruh Afza", current_stock: 3, unit: "Bottle" },
    { item_id: "ITM67", item_name: "Sabut Dhaniya", current_stock: 1, unit: "kg" },
    { item_id: "ITM68", item_name: "Safed Chana (Kabuli Chana Medium)", current_stock: 40, unit: "kg" },
    { item_id: "ITM69", item_name: "Sambhar Masala", current_stock: 10, unit: "Packet" },
    { item_id: "ITM70", item_name: "Sarson", current_stock: 1.5, unit: "kg" },
    { item_id: "ITM71", item_name: "Saunf", current_stock: 1.5, unit: "kg" },
    { item_id: "ITM72", item_name: "Saunth", current_stock: 300, unit: "g" },
    { item_id: "ITM73", item_name: "Sugar", current_stock: 50, unit: "kg" },
    { item_id: "ITM74", item_name: "Suji", current_stock: 30, unit: "kg" },
    { item_id: "ITM75", item_name: "Tej Patta", current_stock: 500, unit: "g" },
    { item_id: "ITM76", item_name: "Urad Sabut", current_stock: 15, unit: "kg" },
    { item_id: "ITM77", item_name: "Wiper", current_stock: 4, unit: "pcs" },
  ];
};
