import mongoose from "mongoose";

const LocationSchema = new mongoose.Schema({
    "Distance from major attractions": { type: String, default: "" },
    "Road condition": { type: String, default: "" },
    "Bus accessibility": { type: String, default: "" },
    "Bus parking": { type: String, default: "" },
    "Safe boarding/deboarding": { type: String, default: "" },
    "Nearby hospital": { type: String, default: "" },
    "Nearby pharmacy": { type: String, default: "" },
    "Mobile network": { type: String, default: "" },
    "Overall location": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const ExteriorSchema = new mongoose.Schema({
    "Overall cleanliness": { type: String, default: "" },
    "Entrance appearance": { type: String, default: "" },
    "Security gate": { type: String, default: "" },
    "Boundary wall": { type: String, default: "" },
    "CCTV coverage": { type: String, default: "" },
    "Night lighting": { type: String, default: "" },
    "Parking area": { type: String, default: "" },
    "Landscaping": { type: String, default: "" },
    "Overall exterior": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const ReceptionSchema = new mongoose.Schema({
    "Reception capacity": { type: String, default: "" },
    "Check-in efficiency": { type: String, default: "" },
    "Reception staff": { type: String, default: "" },
    "Luggage holding area": { type: String, default: "" },
    "Waiting area": { type: String, default: "" },
    "Washrooms": { type: String, default: "" },
    "Drinking water": { type: String, default: "" },
    "Hospitality": { type: String, default: "" },
    "Overall reception": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const RoomsSchema = new mongoose.Schema({
    "Room size": { type: String, default: "" },
    "Bed & mattress": { type: String, default: "" },
    "Bedsheet & linen": { type: String, default: "" },
    "Pillow quality": { type: String, default: "" },
    "Towels": { type: String, default: "" },
    "Door lock": { type: String, default: "" },
    "Window lock": { type: String, default: "" },
    "Balcony safety": { type: String, default: "" },
    "Lighting": { type: String, default: "" },
    "AC": { type: String, default: "" },
    "Fan": { type: String, default: "" },
    "Heater": { type: String, default: "" },
    "TV": { type: String, default: "" },
    "Cupboard": { type: String, default: "" },
    "Tea/Coffee maker": { type: String, default: "" },
    "Charging points": { type: String, default: "" },
    "Wi-Fi": { type: String, default: "" },
    "Mobile network": { type: String, default: "" },
    "Room odour": { type: String, default: "" },
    "Luggage space": { type: String, default: "" },
    "Overall room condition": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const BathroomsSchema = new mongoose.Schema({
    "Hot water": { type: String, default: "" },
    "Flush": { type: String, default: "" },
    "Wash basin": { type: String, default: "" },
    "Shower": { type: String, default: "" },
    "Water pressure": { type: String, default: "" },
    "Drainage": { type: String, default: "" },
    "Toilet cleanliness": { type: String, default: "" },
    "Exhaust fan": { type: String, default: "" },
    "Mirror": { type: String, default: "" },
    "Soap & toiletries": { type: String, default: "" },
    "Bucket & mug": { type: String, default: "" },
    "Anti-slip flooring": { type: String, default: "" },
    "Odour": { type: String, default: "" },
    "Overall bathroom": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const DiningSchema = new mongoose.Schema({
    "Dining capacity": { type: String, default: "" },
    "Group seating": { type: String, default: "" },
    "Buffet setup": { type: String, default: "" },
    "Buffet counters": { type: String, default: "" },
    "Hand wash area": { type: String, default: "" },
    "Drinking water": { type: String, default: "" },
    "Seating comfort": { type: String, default: "" },
    "Lighting": { type: String, default: "" },
    "Ventilation": { type: String, default: "" },
    "Cleanliness": { type: String, default: "" },
    "Food refill speed": { type: String, default: "" },
    "Queue management": { type: String, default: "" },
    "Overall dining": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const KitchenSchema = new mongoose.Schema({
    "Staff hygiene": { type: String, default: "" },
    "Staff uniforms": { type: String, default: "" },
    "Hair caps": { type: String, default: "" },
    "Gloves": { type: String, default: "" },
    "Clean utensils": { type: String, default: "" },
    "Food storage": { type: String, default: "" },
    "Refrigeration": { type: String, default: "" },
    "Vegetable washing area": { type: String, default: "" },
    "Dishwashing area": { type: String, default: "" },
    "Garbage disposal": { type: String, default: "" },
    "Pest control": { type: String, default: "" },
    "Cooking oil quality": { type: String, default: "" },
    "Overall kitchen hygiene": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const FoodSchema = new mongoose.Schema({
    "Breakfast": { type: String, default: "" },
    "Lunch": { type: String, default: "" },
    "Dinner": { type: String, default: "" },
    "Snacks": { type: String, default: "" },
    "Taste": { type: String, default: "" },
    "Freshness": { type: String, default: "" },
    "Variety": { type: String, default: "" },
    "Presentation": { type: String, default: "" },
    "Portion size": { type: String, default: "" },
    "Hygiene": { type: String, default: "" },
    "Student-friendly menu": { type: String, default: "" },
    "Jain food availability": { type: String, default: "" },
    "Special diet availability": { type: String, default: "" },
    "Overall food quality": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const SafetySchema = new mongoose.Schema({
    "Fire extinguishers": { type: String, default: "" },
    "Smoke detectors": { type: String, default: "" },
    "Fire alarm system": { type: String, default: "" },
    "Emergency exits": { type: String, default: "" },
    "Emergency signage": { type: String, default: "" },
    "First aid kit": { type: String, default: "" },
    "Security guards": { type: String, default: "" },
    "Night security": { type: String, default: "" },
    "CCTV": { type: String, default: "" },
    "Boundary security": { type: String, default: "" },
    "Staircase safety": { type: String, default: "" },
    "Balcony safety": { type: String, default: "" },
    "Electrical safety": { type: String, default: "" },
    "Swimming pool safety": { type: String, default: "" },
    "Overall safety": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const ActivitiesSchema = new mongoose.Schema({
    "Adventure equipment": { type: String, default: "" },
    "Safety gear": { type: String, default: "" },
    "Helmets": { type: String, default: "" },
    "Harness": { type: String, default: "" },
    "Certified instructors": { type: String, default: "" },
    "SOP availability": { type: String, default: "" },
    "Indoor games": { type: String, default: "" },
    "Outdoor games": { type: String, default: "" },
    "Bonfire area": { type: String, default: "" },
    "DJ area": { type: String, default: "" },
    "Amphitheatre": { type: String, default: "" },
    "Garden": { type: String, default: "" },
    "Sports ground": { type: String, default: "" },
    "Swimming pool": { type: String, default: "" },
    "Overall recreation": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const MedicalSchema = new mongoose.Schema({
    "Doctor on call": { type: String, default: "" },
    "Ambulance": { type: String, default: "" },
    "First aid room": { type: String, default: "" },
    "First aid box": { type: String, default: "" },
    "Wheelchair": { type: String, default: "" },
    "Emergency contacts": { type: String, default: "" },
    "Overall medical preparedness": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const StaffSchema = new mongoose.Schema({
    "Courtesy": { type: String, default: "" },
    "Grooming": { type: String, default: "" },
    "Uniform": { type: String, default: "" },
    "Communication": { type: String, default: "" },
    "Reception staff": { type: String, default: "" },
    "Restaurant staff": { type: String, default: "" },
    "Housekeeping staff": { type: String, default: "" },
    "Security staff": { type: String, default: "" },
    "Group handling experience": { type: String, default: "" },
    "Overall professionalism": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const CommercialSchema = new mongoose.Schema({
    "Driver accommodation": { type: String, default: "" },
    "Driver meals": { type: String, default: "" },
    "Welcome drink": { type: String, default: "" },
    "Bonfire inclusion": { type: String, default: "" },
    "DJ inclusion": { type: String, default: "" },
    "Activities inclusion": { type: String, default: "" },
    "Early check-in": { type: String, default: "" },
    "Late check-out": { type: String, default: "" },
    "Packed breakfast": { type: String, default: "" },
    "Packed lunch": { type: String, default: "" },
    "Late dinner": { type: String, default: "" },
    "Meal customization": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const ImagedocumentationSchema = new mongoose.Schema({
    "Hotel entrance": { type: String, default: "" },
    "Parking": { type: String, default: "" },
    "Reception": { type: String, default: "" },
    "Standard rooms": { type: String, default: "" },
    "Washrooms": { type: String, default: "" },
    "Dining hall": { type: String, default: "" },
    "Adventure area": { type: String, default: "" },
    "Play area": { type: String, default: "" },
    "Fire extinguishers": { type: String, default: "" },
    "Emergency exits": { type: String, default: "" },
    "View": { type: String, default: "" },
    "Corridors": { type: String, default: "" },
    "Staircases": { type: String, default: "" },
    "Bus parking": { type: String, default: "" },
    "Night lighting": { type: String, default: "" },
    "Review": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const FinalReviewSchema = new mongoose.Schema({
    "Overall hotel score": { type: String, default: "" },
    "Strengths": { type: String, default: "" },
    "Weaknesses": { type: String, default: "" },
    "Critical observations": { type: String, default: "" },
    score: { type: Number, default: 0 },
}, { _id: false });

const recciSchema = new mongoose.Schema({
    schoolName: { type: String, required: [true, "School/Hotel Name is required"] },
    coordinatorName: { type: String, required: [true, "Coordinator Name is required"] },
    travelDate: { type: String, required: [true, "Travel Date is required"] },
    location: { type: String, required: [true, "Location is required"] },

    "Location": LocationSchema,
    "Exterior": ExteriorSchema,
    "Reception": ReceptionSchema,
    "Rooms": RoomsSchema,
    "Bathrooms": BathroomsSchema,
    "Dining": DiningSchema,
    "Kitchen": KitchenSchema,
    "Food": FoodSchema,
    "Safety": SafetySchema,
    "Activities": ActivitiesSchema,
    "Medical": MedicalSchema,
    "Staff": StaffSchema,
    "Commercial": CommercialSchema,
    "Image documentation": ImagedocumentationSchema,
    "Final Review": FinalReviewSchema,
}, { timestamps: true });

const RecciModel = mongoose.models.Recci || mongoose.model("Recci", recciSchema);

export default RecciModel;
